### ISSUE TITLE
Video encoding

### ISSUE THREAD

**Issue by MuhammadFaizanArif** [Zylern/TGVid-Comp#11]
Video I want to encode but its not encoding when i use preset faster or fast not working only the preset working is ultrafast but   the video quality is very bad using this preset :  video info link (  https://spaceb.in/raySncvg   ) 
And (/setcode -preset faster -c:v libx265 -s 860x480 -x264-params 'bframes=8:psy-rd=1:ref=3:aq-mode=3:aq-strength=0.8:deblock=1,1' -metadata 'title=Encoded By (https://t.me/animedualaudiozippercartoonist )' -metadata:s:v title="@animecolony" -metadata:s:a title="@animecolony" -metadata:s:s title="@animecolony" -pix_fmt yuv420p -crf 26 -c:a libopus -b:a 32k -c:s copy -map 0 -ac 2 -ab 32k -vbr 2 -level 3.1 -threads 1 )
this is the code i use

 can you tell me about any solution to encode the video

**Comment by Helpless69** [comment]
`-x264-params`
Since when did x264 started using -params😂
Btw I recommend you to use fast preset instead of faster
Here I fixed typo
`/setcode -preset faster -c:v libx265 -s 860x480 -x265-params 'bframes=8:psy-rd=1:ref=3:aq-mode=3:aq-strength=0.8:deblock=1,1' -metadata 'title=Encoded By (https://t.me/animedualaudiozippercartoonist )' -metadata:s:v title="@animecolony" -metadata:s:a title="@animecolony" -metadata:s:s title="@animecolony" -pix_fmt yuv420p -crf 26 -c:a libopus -b:a 32k -c:s copy -map 0 -ac 2 -ab 32k -vbr 2 -level 3.1 -threads 1`

**Comment by MuhammadFaizanArif** [comment]
Not working i know about the ffmpeg code i also change the code but the
video isn't encoding

**Comment by Zylern** [comment]
Not bot issue some videos cannot be re-encoded using ffmpeg you will get error while encoding them.

**Comment by MuhammadFaizanArif** [comment]
Then whey the bot encode the video in ultrafast preset
Preset fast faster not working but when i only change ultrafast it work

**Comment by Helpless69** [comment]
Ultrafast present requires low cpu power and encode video faster but gives worse quality encodes and hence low end servers like Heroku and Railway can run them easily.

Fast/Faster preset will give you better quality encodes at longer encode time but requires a decent cpu to encode videos
